### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by g4s8** [akuleshov7/git-stat#6]
I built app using `./gradlew build`, it generates file `./gradle/wrapper/gradle-wrapper.jar`. But when I started it, with
```
java -jar ./build/libs/git-stat-1.0-SNAPSHOT.jar
````
it fails with error:
> no main manifest attribute, in ./build/libs/git-stat-1.0-SNAPSHOT.jar

**Comment by orchestr7** [comment]
I will prepare a build today and fix gradle. Also will add actions for the build.
Idea project by the default adds manifest.

**Comment by orchestr7** [comment]
Btw - I really hate Gradle!!!! )
@g4s8

**Comment by g4s8** [comment]
@akuleshov7 I'm not sure about Gradle and manifest files, but maybe this SO answer can help you: https://stackoverflow.com/a/9689877/1723695
```
jar {
    manifest {
        attributes(
                'Main-Class': 'com.mypackage.MyClass'
        )
    }
}
```

**Comment by orchestr7** [comment]
> @akuleshov7 I'm not sure about Gradle and manifest files, but maybe this SO answer can help you: https://stackoverflow.com/a/9689877/1723695
> 
> ```
> jar {
>     manifest {
>         attributes(
>                 'Main-Class': 'com.mypackage.MyClass'
>         )
>     }
> }
> ```

yeah, yeah, I know about this :) Simply have forgotten due to Idea that adds manifest
